version: '3'

services:
    # Etherpad: real-time collaborative document editing
    etherpad:
        image: za_jitsi/etherpad:latest
        restart: ${RESTART_POLICY}
        networks:
            meet.jitsi:
                aliases:
                    - etherpad.meet.jitsi
